services:
  postgres:
    image: postgres:16
    container_name: resq_postgres
    environment:
      POSTGRES_DB: ${DB_URL}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - resq_pgdata:/var/lib/postgresql/data